name: CI

on:
  push:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        run: |
          set -xe
          
          npm install --save-dev jest
          npm test
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        run: |
          set -xe
          
          # Docker lint install and run
          sudo npm install -g dockerlint
          dockerlint -f Dockerfile

          # Helm lint
          # set current working dir
          WORKDIR=$(pwd)
          cd /tmp/
          # Download and install helm client
          wget https://get.helm.sh/helm-v3.4.2-linux-amd64.tar.gz
          tar -zxvf helm-v3.4.2-linux-amd64.tar.gz
          ls -l
          PATH=$PATH:/tmp/linux-amd64/
          cd $WORKDIR
          helm version --client

          # run helm lint
          helm lint chart/nodejs-starter/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        run: |
          set -xe
          
          #echo "$DOCKER_LOGIN" | docker login us.icr.io -u "iamapikey" --password-stdin
          docker build .

